import { NextRequest, NextResponse } from "next/server";
import { generateIdeas } from "@/services/ideaGeneratorService";
import type { ApiResponse, ContentIdea, GenerateIdeasInput } from "@/types";

/**
 * POST /api/ideas/generate
 * Generates 5 rule-based content ideas.
 * Does NOT require MongoDB — works standalone.
 */
export async function POST(request: NextRequest) {
  try {
    const body: GenerateIdeasInput = await request.json();

    if (!body.topic || !body.platform || !body.tone || !body.targetAudience) {
      return NextResponse.json<ApiResponse>(
        { success: false, error: "Missing required fields: topic, platform, tone, targetAudience" },
        { status: 400 }
      );
    }

    const { ideas, source } = await generateIdeas(body);

    return NextResponse.json<ApiResponse<{ ideas: ContentIdea[], source: "AI" | "Rule-based" }>>({
      success: true,
      data: { ideas, source },
      message: `Generated by ${source}`,
    });
  } catch (error) {
    console.error("[/api/ideas/generate]", error);
    return NextResponse.json<ApiResponse>(
      { success: false, error: "Failed to generate ideas" },
      { status: 500 }
    );
  }
}
